"""
Workflow Enumerations Module.

This module defines all enumerations used throughout the workflows subsystem.
"""

from enum import Enum

from .constants import (
    # Node Types
    NODE_TYPE_AGENT,
    NODE_TYPE_TOOL,
    NODE_TYPE_DECISION,
    NODE_TYPE_PARALLEL,
    NODE_TYPE_LOOP,
    NODE_TYPE_SUBWORKFLOW,
    NODE_TYPE_TRANSFORM,
    NODE_TYPE_WEBHOOK,
    NODE_TYPE_DELAY,
    NODE_TYPE_HUMAN_INPUT,
    NODE_TYPE_START,
    NODE_TYPE_END,
    NODE_TYPE_ERROR_HANDLER,
    NODE_TYPE_CUSTOM,
    # Edge Types
    EDGE_TYPE_DEFAULT,
    EDGE_TYPE_CONDITIONAL,
    EDGE_TYPE_FALLBACK,
    EDGE_TYPE_TIMEOUT,
    EDGE_TYPE_ERROR,
    EDGE_TYPE_LOOP_BACK,
    EDGE_TYPE_PARALLEL_JOIN,
    EDGE_TYPE_CUSTOM,
    # Workflow States
    WORKFLOW_STATE_IDLE,
    WORKFLOW_STATE_RUNNING,
    WORKFLOW_STATE_PAUSED,
    WORKFLOW_STATE_COMPLETED,
    WORKFLOW_STATE_FAILED,
    WORKFLOW_STATE_CANCELLED,
    WORKFLOW_STATE_WAITING,
    # Node States
    NODE_STATE_PENDING,
    NODE_STATE_RUNNING,
    NODE_STATE_COMPLETED,
    NODE_STATE_FAILED,
    NODE_STATE_SKIPPED,
    NODE_STATE_WAITING,
    # Condition Operators
    CONDITION_OP_EQUALS,
    CONDITION_OP_NOT_EQUALS,
    CONDITION_OP_CONTAINS,
    CONDITION_OP_NOT_CONTAINS,
    CONDITION_OP_GREATER_THAN,
    CONDITION_OP_LESS_THAN,
    CONDITION_OP_GREATER_OR_EQUAL,
    CONDITION_OP_LESS_OR_EQUAL,
    CONDITION_OP_IS_EMPTY,
    CONDITION_OP_IS_NOT_EMPTY,
    CONDITION_OP_MATCHES_REGEX,
    CONDITION_OP_STARTS_WITH,
    CONDITION_OP_ENDS_WITH,
    CONDITION_OP_IN_LIST,
    CONDITION_OP_NOT_IN_LIST,
    CONDITION_OP_IS_TRUE,
    CONDITION_OP_IS_FALSE,
    CONDITION_OP_CUSTOM,
    # Routing Strategies
    ROUTING_STRATEGY_FIRST_MATCH,
    ROUTING_STRATEGY_ALL_MATCHES,
    ROUTING_STRATEGY_WEIGHTED,
    ROUTING_STRATEGY_ROUND_ROBIN,
    ROUTING_STRATEGY_RANDOM,
    ROUTING_STRATEGY_LLM_BASED,
    ROUTING_STRATEGY_CUSTOM,
    # Execution Modes
    EXECUTION_MODE_SEQUENTIAL,
    EXECUTION_MODE_PARALLEL,
    EXECUTION_MODE_STREAMING,
)


class NodeType(str, Enum):
    """Types of nodes available in workflows."""
    
    AGENT = NODE_TYPE_AGENT
    TOOL = NODE_TYPE_TOOL
    DECISION = NODE_TYPE_DECISION
    PARALLEL = NODE_TYPE_PARALLEL
    LOOP = NODE_TYPE_LOOP
    SUBWORKFLOW = NODE_TYPE_SUBWORKFLOW
    TRANSFORM = NODE_TYPE_TRANSFORM
    WEBHOOK = NODE_TYPE_WEBHOOK
    DELAY = NODE_TYPE_DELAY
    HUMAN_INPUT = NODE_TYPE_HUMAN_INPUT
    START = NODE_TYPE_START
    END = NODE_TYPE_END
    ERROR_HANDLER = NODE_TYPE_ERROR_HANDLER
    CUSTOM = NODE_TYPE_CUSTOM


class EdgeType(str, Enum):
    """Types of edges connecting nodes in workflows."""
    
    DEFAULT = EDGE_TYPE_DEFAULT
    CONDITIONAL = EDGE_TYPE_CONDITIONAL
    FALLBACK = EDGE_TYPE_FALLBACK
    TIMEOUT = EDGE_TYPE_TIMEOUT
    ERROR = EDGE_TYPE_ERROR
    LOOP_BACK = EDGE_TYPE_LOOP_BACK
    PARALLEL_JOIN = EDGE_TYPE_PARALLEL_JOIN
    CUSTOM = EDGE_TYPE_CUSTOM


class WorkflowState(str, Enum):
    """Possible states of a workflow execution."""
    
    IDLE = WORKFLOW_STATE_IDLE
    RUNNING = WORKFLOW_STATE_RUNNING
    PAUSED = WORKFLOW_STATE_PAUSED
    COMPLETED = WORKFLOW_STATE_COMPLETED
    FAILED = WORKFLOW_STATE_FAILED
    CANCELLED = WORKFLOW_STATE_CANCELLED
    WAITING = WORKFLOW_STATE_WAITING


class NodeState(str, Enum):
    """Possible states of a node during execution."""
    
    PENDING = NODE_STATE_PENDING
    RUNNING = NODE_STATE_RUNNING
    COMPLETED = NODE_STATE_COMPLETED
    FAILED = NODE_STATE_FAILED
    SKIPPED = NODE_STATE_SKIPPED
    WAITING = NODE_STATE_WAITING


class ConditionOperator(str, Enum):
    """Operators for edge conditions."""
    
    EQUALS = CONDITION_OP_EQUALS
    NOT_EQUALS = CONDITION_OP_NOT_EQUALS
    CONTAINS = CONDITION_OP_CONTAINS
    NOT_CONTAINS = CONDITION_OP_NOT_CONTAINS
    GREATER_THAN = CONDITION_OP_GREATER_THAN
    LESS_THAN = CONDITION_OP_LESS_THAN
    GREATER_OR_EQUAL = CONDITION_OP_GREATER_OR_EQUAL
    LESS_OR_EQUAL = CONDITION_OP_LESS_OR_EQUAL
    IS_EMPTY = CONDITION_OP_IS_EMPTY
    IS_NOT_EMPTY = CONDITION_OP_IS_NOT_EMPTY
    MATCHES_REGEX = CONDITION_OP_MATCHES_REGEX
    STARTS_WITH = CONDITION_OP_STARTS_WITH
    ENDS_WITH = CONDITION_OP_ENDS_WITH
    IN_LIST = CONDITION_OP_IN_LIST
    NOT_IN_LIST = CONDITION_OP_NOT_IN_LIST
    IS_TRUE = CONDITION_OP_IS_TRUE
    IS_FALSE = CONDITION_OP_IS_FALSE
    CUSTOM = CONDITION_OP_CUSTOM


class RoutingStrategy(str, Enum):
    """Strategies for routing between nodes."""
    
    FIRST_MATCH = ROUTING_STRATEGY_FIRST_MATCH
    ALL_MATCHES = ROUTING_STRATEGY_ALL_MATCHES
    WEIGHTED = ROUTING_STRATEGY_WEIGHTED
    ROUND_ROBIN = ROUTING_STRATEGY_ROUND_ROBIN
    RANDOM = ROUTING_STRATEGY_RANDOM
    LLM_BASED = ROUTING_STRATEGY_LLM_BASED
    CUSTOM = ROUTING_STRATEGY_CUSTOM


class ExecutionMode(str, Enum):
    """Modes of workflow execution."""
    
    SEQUENTIAL = EXECUTION_MODE_SEQUENTIAL
    PARALLEL = EXECUTION_MODE_PARALLEL
    STREAMING = EXECUTION_MODE_STREAMING


class DataTransformType(str, Enum):
    """Types of data transformations between nodes."""
    
    PASS_THROUGH = "pass_through"
    MAP = "map"
    FILTER = "filter"
    REDUCE = "reduce"
    MERGE = "merge"
    SPLIT = "split"
    EXTRACT = "extract"
    FORMAT = "format"
    TEMPLATE = "template"
    JMESPATH = "jmespath"
    JSONPATH = "jsonpath"
    PYTHON = "python"
    CUSTOM = "custom"


class TriggerType(str, Enum):
    """Types of workflow triggers."""
    
    MANUAL = "manual"
    SCHEDULED = "scheduled"
    WEBHOOK = "webhook"
    EVENT = "event"
    API = "api"
    MESSAGE = "message"
    FILE = "file"
    CUSTOM = "custom"


class RetryStrategy(str, Enum):
    """Strategies for retrying failed nodes."""
    
    NONE = "none"
    FIXED = "fixed"
    EXPONENTIAL_BACKOFF = "exponential_backoff"
    LINEAR_BACKOFF = "linear_backoff"
    CUSTOM = "custom"

